server:
  port: 7001


# eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false   #表示自己为server
    register-with-eureka: false  #是否向服务中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


